#!/bin/bash
set -e

# Load .env file
ENV_FILE="$(dirname "$0")/../.env"
if [ -f "$ENV_FILE" ]; then
    export $(grep -v '^#' "$ENV_FILE" | sed 's/\r$//' | xargs)
else
    echo "Missing .env file at $ENV_FILE"
    exit 1
fi

# Validate required variables
REQUIRED_VARS=("PROJECT_NAME" "PROJECT_DIR" "UNREAL_VERSION")
for VAR in "${REQUIRED_VARS[@]}"; do
  if [ -z "${!VAR}" ]; then
    echo "Error: Required env var $VAR not set"
    exit 1
  fi
done

# Resolve target file path
TARGET_CS_PATH="${PROJECT_DIR}/${PROJECT_NAME}Server.Target.cs"

# Generate file
cat > "$TARGET_CS_PATH" <<EOF
// Auto-generated by gen_server_target.sh

using UnrealBuildTool;
using System.Collections.Generic;

public class ${PROJECT_NAME}ServerTarget : TargetRules
{
    public ${PROJECT_NAME}ServerTarget(TargetInfo Target) : base(Target)
    {
        Type = TargetType.Server;
        DefaultBuildSettings = BuildSettingsVersion.V2;
        IncludeOrderVersion = EngineIncludeOrderVersion.Unreal${UNREAL_VERSION};
        ExtraModuleNames.Add("${PROJECT_NAME}");
    }
}
EOF

echo "Generated: $TARGET_CS_PATH"
